import com.library.service.BookService;
import org.springframework.context.ApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class RunExercise6 {
    public static void main(String[] args) {
        // 1. Initialize Spring context container
        ApplicationContext context = new ClassPathXmlApplicationContext("applicationContext.xml");

        // 2. Fetch the bean using the default bean name generated by Spring (camelCase of the class name)
        BookService service = (BookService) context.getBean("bookService");

        // 3. Test execution
        service.runService();
    }
}